### ISSUE TITLE
netcdf package naming

### ISSUE THREAD

**Issue by SteVwonder** [ctuning/ck-scc18#3]
On the [shared packages](http://cknowledge.org/shared-packages.html) site and in ck CLI calls, netcdf is listed as `lib-netcdf-4-4.1`.  I believe it should actually be `lib-netcdf-4.4.1` (note the two periods rather than two dashes). I presume renaming [this directory](https://github.com/ctuning/ck-scc18/tree/master/package/lib-netcdf-4-4.1) and editing [this info file](https://github.com/ctuning/ck-scc18/blob/master/package/lib-netcdf-4-4.1/.cm/info.json) would fix it.

**Comment by gfursin** [comment]
Thanks @SteVwonder - I fixed that. It's done from CMD as follows:
```
$ ck ren lib-netcdf-4-4.1 lib-netcdf-4.4.1 --share
```
Since we keep track of aliases, UIDs and other info in the .cm directory, it's better to do it via CK. In such case CK will update all internal info automatically. --share flag also tells to update shared files/dirs via Git ...
