### ISSUE TITLE
can't install mpi version thorugh ck

### ISSUE THREAD

**Issue by daisy20170101** [ctuning/ck-scc18#5]
I tried to install seissol through ck but it didn'k work. It crashed down with hdf5. Here are the reporst.

Thanks for any suggestion!

Makefile:553: recipe for target 'h5tools_str.lo' failed
make[2]: *** [h5tools_str.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:553: recipe for target 'h5tools_dump.lo' failed
make[2]: *** [h5tools_dump.lo] Error 1
../../../hdf5-1.8.11/tools/lib/h5tools.c:1549:8: warning: 'type_id' may be used uninitialized in this function [-Wmaybe-uninitialized]
     if(H5Tclose(type_id) < 0)
        ^
../../../hdf5-1.8.11/tools/lib/h5tools.c: In function 'render_bin_output_region_blocks':
../../../hdf5-1.8.11/tools/lib/h5tools.c:1437:8: warning: 'type_id' may be used uninitialized in this function [-Wmaybe-uninitialized]
     if(H5Tclose(type_id) < 0)
        ^
../../../hdf5-1.8.11/tools/lib/h5tools.c:1440:8: warning: 'dtype' may be used uninitialized in this function [-Wmaybe-uninitialized]
     if(H5Tclose(dtype) < 0)
        ^
make[2]: Leaving directory '/import/deadlock-data/dli/CK-TOOLS/lib-hdf5-static-1.8.11-gcc-4.9.2-lib.mpi-2.1.5-linux-64/obj/tools/lib'
Makefile:497: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/import/deadlock-data/dli/CK-TOOLS/lib-hdf5-static-1.8.11-gcc-4.9.2-lib.mpi-2.1.5-linux-64/obj/tools'
Makefile:539: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
Error: build failed!

   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   CK detected a PROBLEM in the third-party CK package:

   CK package:           lib-hdf5-1.8.11-parallel-static-src
   Native package URL:   https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.11/src
   CK repo:              ck-env
   CK repo URL:          https://github.com/ctuning/ck-env
   CK package URL:       https://github.com/ctuning/ck-env/tree/master/package/lib-hdf5-1.8.11-parallel-static-src
   Issues URL:           https://github.com/ctuning/ck-env/issues
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Please, submit the log to the authors of this external CK package at "https://github.com/ctuning/ck-env/issues" to collaboratively fix this problem!

**Comment by gfursin** [comment]
Thanks for reporting! May I ask you to attach the full log please? I.e. from the start of the ck command? 
Also, can you please send the following outputs:
```
$ ck detect platform
$ ck show env
```
This can help us understand where the problem happened!
Thanks a lot!

**Comment by psyhtest** [comment]
Closing as no further input. It could be the case of warnings being treated as errors. The GCC version is very old (4.9.2).
